version: "2.3"

services:
  api:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      args:
        PACKAGE: api
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

networks:
  booking:
    driver: bridge